name: CI Cache Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: prime-cache-80947d0
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-80947d0
