name: CI Cache Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-80947d0
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-80947d0

      - name: Echo cache result
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
